spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sbm?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8&nullCatalogMeansCurrent=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: mr.s.dao
  mapper-locations: classpath:mapper/*.xml
logging:
  config: classpath:logback.xml
server:
  port: 8080

